name: 'Nightly'

on:
  workflow_call:

jobs:
  build-checks:
    name: I am scheduled.
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        cc:
          - gcc
      fail-fast: true
    steps:
      - name: 'Checkout repoA'
        uses: actions/checkout@v4
      - name: 'get sha of head of repoA main branch'
        run: |
          pwd
          ls
          which git
          git remote -v
          git ls-remote -q | grep refs/heads/main$ | awk '{print $1}'
          echo ${{ github.sha }}
